name: camera_gallery_image_picker
description: Flutter Package to capture image from camera and pick image from gallery. This Package supports both the feature at a same time or individually.
version: 0.0.1
homepage: https://github.com/Hpaneru/camera_gallery_image_picker

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
